export const FETCH_MOVIE_LIST_REQUEST = 'FETCH_MOVIE_LIST_REQUEST'
export const FETCH_MOVIE_LIST_SUCCESS = 'FETCH_MOVIE_LIST_SUCCESS'
export const FETCH_MOVIE_LIST_FAILED = 'FETCH_MOVIE_LIST_FAILED'
export const CLEAR_MOVIE_LIST = 'CLEAR_MOVIE_LIST'


